#!/usr/bin/env bash
#Script prints string using until, prints different string on 9th iteration
#!/bin/bash

count=1

while [ $count -le 10 ]; do
  if [ $count -eq 9 ]; then
    echo -e "Hi"
  else
    echo "Best School"
  fi
  count=$((count + 1))
done

