#!/usr/bin/env bash
#Script loops through numbers, displays distinct strings at iteration 4, 9, 17

count=1

while [ $count -le 20 ]; do
  case $count in
    4)
      echo -e "4\nbad luck from China"
      ;;
    9)
      echo -e "9\nbad luck from Japan"
      ;;
    17)
      echo -e "17\nbad luck from Italy"
      ;;
    *)
      echo $count
      ;;
  esac
  count=$((count + 1))
done
