#!/usr/bin/env bash
# Changes addresses on /etc/hosts for localhost and facebook

cp /etc/hosts ~/hosts.new
sed -i 's/127.*$/127.0.0.2 localhost\n8.8.8.8 facebook.com/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts

